

partitech_sonata_extra.controllers:
  resource:
    path: ../src/Controller/
    namespace: Partitech\SonataExtra\Controller
  type: attribute

#partitech_sonata_extra.routes:
#  type: annotation
#  resource: '../src/'


#admin_route_list:
#  path: /admin/routes
#  controller: App\Controller\Admin\RouteAdminController::listAction
#  methods: GET

partitech_sonata_extra.db.page.routes:
  resource: 'Partitech\SonataExtra\Routing\DatabaseRouteLoader'
  type: 'partitech_db_page_route'
